[package]
name = "cafe-bakery"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "entity" }
actix-web = "4"
sea-orm = { version = "0.12", features = ["debug-print", "runtime-tokio-native-tls", "sqlx-mysql", "macros" ] }


